LOCAL_PATH := $(call my-dir)

PREBUILT_PATH := $(LOCAL_PATH)/../../prebuilt
LIB_X264_PATH := $(PREBUILT_PATH)/x264
LIB_X264_LIB := ../$(LIB_X264_PATH)/$(TARGET_ARCH_ABI)/lib

include $(CLEAR_VARS)
LOCAL_MODULE := x264
LOCAL_SRC_FILES := $(LIB_X264_LIB)/libx264.a
include $(PREBUILT_STATIC_LIBRARY)

include $(CLEAR_VARS)

LOCAL_MODULE    := x264Encoder

LOCAL_C_INCLUDES := $(LOCAL_PATH)
LOCAL_C_INCLUDES += $(PREBUILT_PATH)/include
LOCAL_C_INCLUDES += $(LIB_X264_PATH)/$(TARGET_ARCH_ABI)/include

LOCAL_SRC_FILES := x264Encoder.c \
				   jni_X264EncoderWrapper.c

LOCAL_STATIC_LIBRARIES := x264
LOCAL_LDLIBS += -llog

include $(BUILD_SHARED_LIBRARY)